### ISSUE TITLE
Add URL exceptions

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/urlfix#1]
**Description**

I would like to exclude some URLs from being replaced.

**Similar Features**

This will be similar to the replacement method once it's in place.

**Feature Details**

Exclude certain URLs from the replacement. If I have a URL like that of Zenodo that I know is correct (links that allow citing the latest version of multiple releases), this should be skipped when replacing.

**Proposed Implementation**

Write a RegEx to skip such links.

**Comment by nirolada** [comment]
But in order to skip it, you first need to check if it's correct, and in order to check if it's correct, you need to urlib open it and compare visited url with input url... Am I wrong?

**Comment by Nelson-Gon** [comment]
Thanks for the suggestion. The idea I had in mind was that if I know that a link is correct, then it is resource saving to simply skip checking it.

For example, the DOI link in the README of this repository if checked would apppear to have moved but in reality, this DOI simply links to the latest version sions on Zenodo. In

**Comment by nirolada** [comment]
Would you like to save/log correct urls (up-to-date or fixed ones) somewhere? Or maybe get a tuple of correct urls as an argument for the 'replace-urls' method?

**Comment by Nelson-Gon** [comment]
Ideally, the first part. I was thinking of some sort of caching to avoid continously checking already known uptodate links. A tuple/list of known fixed urls argument sounds good too!

**Comment by nirolada** [comment]
Assign it to me.
