### ISSUE TITLE
Replace outdated URLs inplace

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/urlfix#10]
**Description**

Replace outdated URLs in the same file. 

**Similar Features**

This is similar to `replace_urls` in `URLFix` and `DirURLFix`. The issue with the current replacements is that the former requires an output file while the latter creates them on-the-fly. 

**Feature Details**

Using output files may create a lot of files in the user's system which may be problematic for users with low storage space. 
**Proposed Implementation**

Create temporary files to write to before renaming them as the input file.

**Comment by spradhan92** [comment]
I would like to work on this @Nelson-Gon .

**Comment by spradhan92** [comment]
Hi @Nelson-Gon ,
One question.
I want to understand whether after renaming the temp files to the input files we want to delete the "original" input files as well?

**Comment by Nelson-Gon** [comment]
@spradhan92 Ideally, as long as it conserves the original data in the file. The main idea is to avoid creating so many files in a user's environment. Thanks!
