### ISSUE TITLE
Requirements.txt doesn't specify urllib version

### ISSUE THREAD

**Issue by mattwilson888** [Nelson-Gon/urlfix#14]
**Describe the bug**
When setting up the virtual environment, the urllib library version is not specified in the `requirements.txt` file thus it uses the system default.

**To Reproduce**
1. Clone a clean branch of the repo, check the system's version of `urllib` using (Linux) `pip show urllib`.
2. Create the virtual env `python3 -m venv urlvenv` and install requirements `pip install -r requirements.txt`
3. Check the urllib version again, see that it matches the sysem default.

**Expected behavior**

Version of urllib specific to the source code to be explicitly installed.

**Unexpected behavior**

System default version of urllib is used when running the source code. The only version of urllib installed inside or outside the venv setup with the current `requirements.txt` file is `urllib3==1.26.3`, which is in fact the latest release (perhaps this is intentional).

**System Details**

Arch Linux.
Pip 20.2.3
Python 3.9

**Comment by mattwilson888** [comment]
I guess urllib is in the standard library, but urllib3 is not - hence the confusion.

**Comment by Nelson-Gon** [comment]
Hi, thanks and sorry for the confusion.
