### ISSUE TITLE
Output .md file is losing those line which are not having url while same is working fine for  .txt file

### ISSUE THREAD

**Issue by spradhan92** [Nelson-Gon/urlfix#16]
**Describe the bug**
The output .md file is losing texts which don't have URL links in them

**To Reproduce**
Run the code with .md file which has text without URLs in the same line.

Input file:
![image](https://user-images.githubusercontent.com/64601292/110245262-b7aca680-7f62-11eb-8d87-ffb48ba3af66.png)

**Expected behavior**
There should be no text loss other than changing of the old URLs.

**Unexpected behavior**
Only the lines with URLs are being generated in the output file.
Output file:
![image](https://user-images.githubusercontent.com/64601292/110245356-fb071500-7f62-11eb-8116-13ca2e7a1899.png)

**Comment by Nelson-Gon** [comment]
Hi,

Thanks for reporting. I will check this out tomorrow. In the meantime, could you please add the hash code for which this issue occurs and the code run?

**Comment by Nelson-Gon** [comment]
I can reproduce this. Will take a look.

**Comment by Nelson-Gon** [comment]
TODO:

[ x ] Ensure text is kept

[  ] Match all URLs for Markdown in the form `[[]]()()`

[  ] Add tests for known string existence

**Comment by Nelson-Gon** [comment]
Hi, @spradhan92 Can you still reproduce this issue with the latest dev push? https://github.com/Nelson-Gon/urlfix/tree/4212bad4503cca5ae53f694c7bf623ca6d66fbf5/urlfix

**Comment by spradhan92** [comment]
Hi, @Nelson-Gon
No, I am not. The latest dev push is working fine for the md files as well as txt files.

**Comment by Nelson-Gon** [comment]
Cool, thanks for the feedback!
