### ISSUE TITLE
Warn if the target URL no longer exists

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/urlfix#18]
**Description**

If a URL is outdated and no new link exists, warn the user.

**Similar Features**

This is similar to `replace_urls`.

**Feature Details**

if url.is_outdated and url.redirects.status == 404:
user.warn
old_url.keep

The above is pseudocode that hopefully makes it clear what should be done.

**Proposed Implementation**

As above.

**Comment by dineshkumar-23** [comment]
Hi, I would like to work on this. I believe this feature needs to be added as a separate method like replace_urls under class URLFix. Is that right?

**Comment by Nelson-Gon** [comment]
Hi @dineshkumar-23 I have not looked into it that much but I think it would suffice to add a check within `replace_urls` probably after `urlopen`. If status is not 200 or specifically if it is 404,then for that URL simply warm the user and leave it intact.

**Comment by dineshkumar-23** [comment]
Sounds good. I'll try this approach...

**Comment by Nelson-Gon** [comment]
Great, thanks!
