### ISSUE TITLE
Move to Classes

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/urlfix#3]
**Description**

A proposal to implement a class or classes as opposed to standalone methods. 

**Similar Features**

N/A

**Feature Details**

Using a class would provide an easier way to work with several files, improve readability, and provide greater control. 

**Proposed Implementation**

Implement class `URLFix`

**Comment by TawfikYasser** [comment]
Hi @Nelson-Gon Can i add the class `URLFix` ?

**Comment by Nelson-Gon** [comment]
Sure, thank you!

**Comment by TawfikYasser** [comment]
Okay, Please explain what should done ?

**Comment by Nelson-Gon** [comment]
Here is what I think should be done:

- [ ] Create a class named `URLFix` which takes an `input_file`

- [ ] Change all methods except `find_links` to class methods.
- [ ] Make `find_links` a non class method
- [ ] Proceed as stated in the [contributing file](https://github.com/Nelson-Gon/urlfix/tree/master/.github/CONTRIBUTING.md)

**Comment by TawfikYasser** [comment]
Okay @Nelson-Gon Thank you, I will start.

**Comment by Nelson-Gon** [comment]
Sorry @TawfikYasser I had to implement to make it easier to work on new features. I am happy for you to help with something else that you may find interesting. Thank you!
