### ISSUE TITLE
Automatically detect file extension in replace_urls

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/urlfix#4]
**Description**

The default in `replace_urls(output_file="replacement.txt")` should automatically match the input file's format.

**Similar Features**

This is similar to  `replace_urls(output_file="replacement.txt")` 

**Feature Details**

It has been sufficiently described.

**Proposed Implementation**

Use a regular expression to match the file format and use that.

Thank you

**Comment by nirolada** [comment]
I can take this issue as well if you'd like.

**Comment by Nelson-Gon** [comment]
Closed via #8
