### ISSUE TITLE
Replace URLs in an entire file directory 

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/urlfix#5]
**Description**

I would like to replace outdated URLs in all files in a given directory.

**Similar Features**

Currently `replace_urls` only accepts a single file. 

**Feature Details**

The feature has been well described.

**Proposed Implementation**

* Provide a `directory` argument. 
* Loop over all files and replace URLs in each file. This may be computationally slow.

**Comment by hiteshbhavsar** [comment]
Hey I am completely new to the term open source development, Can you suggest how can I contribute to this issue?

**Comment by Nelson-Gon** [comment]
Hello,

Thank you for your interest in contributing to `urlfix`. If you would like to tackle this specific issue, here is what I had in mind as a proposed implementation:

* Currently, `replace_urls` reads all links in a single file and updates them, if they are outdated.
* The idea now is to walk/loop over an entire directory containing `.md` files for example and replace URLs in them. One simple way to do this would be to 
    - List all files that match the target file type for example by using `glob`.
    - Using a list comprehension or loop, feed the file from above to `replace_urls` eg [replace_urls(x) for x in files_found]`
    - Otherwise, a better way might be to make `replace_urls` have this feature natively.

If that sounds fine, please implement in a fork and create a pull request which I will be happy to review.  

Finally, please ensure that all steps outlined in the  contributing [guide](https://github.com/Nelson-Gon/urlfix/blob/master/.github/CONTRIBUTING.md) are followed. 

Thank you very much,

Nelson

**Comment by nirolada** [comment]
Hi, I'd like to take the issue.

**Comment by Nelson-Gon** [comment]
Hi @nirolada,

Thank you for your interest in this project. I will assign this issue to you and will be glad to review your pull request. 

Best wishes, 

Nelson

**Comment by nirolada** [comment]
@Nelson-Gon is there anywhere I can chat with you about the issue? slack, discord etc.

**Comment by Nelson-Gon** [comment]
@nirolada I do not have Slack/Discord. I have setup a Discussions page where discussions can be made. Please find it [here](https://github.com/Nelson-Gon/urlfix/discussions/) and start a new discussion.
